import Head from 'next/head'
import Image from 'next/image'
import Feed from "../components/Feed";
import styles from '../styles/Home.module.css'
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";
import CommentModal from '../components/CommentModal';
export default function Home({ newResults,randomUsersResults }) {

  console.log(newResults)
  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


<div>

<main className="flex min-h-screen mx-auto">
        {/* Sidebar */}
        <Sidebar />

        {/* Feed */}

        <Feed />

        {/* Widgets */}

        <Widgets newResults={newResults.articles} randomUsersResults={randomUsersResults.results}/>

        {/* Modal */}

        <CommentModal />
      </main>











</div>


    
    </div>
  )
}

export async function getServerSideProps(){
  const newResults = await fetch ("https://saurav.tech/NewsAPI/top-headlines/category/business/us.json").then((res) => res.json());

  const randomUsersResults = await fetch("https://randomuser.me/api/?results=30&inc=name,login,picture").then((res) => res.json());

  return {
    props: {
      newResults,
      randomUsersResults
    }
  }
}